{% set name = "aioboto3" %}
{% set version = "10.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 212cd30334e203cadc6389c526478cc6eaba266589637f5df2133c76f97b8544

build:
  noarch: python
  number: 0
  script: rm -f poetry.lock && {{ PYTHON }} -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
    - poetry
    - poetry-dynamic-versioning
  run:
    - python >=3.8
    - aiobotocore ==2.4.0
    - boto3 >=1.21.21
    - cryptography >=37.0.0
    - idna >=3.3.0


test:
  imports:
    - aioboto3
    - aioboto3.s3

about:
  home: https://github.com/terrycain/aioboto3
  summary: 'Wrapper to use boto3 resources with the aiobotocore async backend'
  description: |
    aiobotocore allows you to use near enough all of the boto3 client commands in an async manner just by prefixing the command with await.
  home: https://github.com/terrycain/aioboto3
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://aioboto3.readthedocs.io/en/latest/
  dev_url: https://github.com/terrycain/aioboto3

extra:
  recipe-maintainers:
    - dgasmith
    - skrsna
    - markllama
